---
title: "The New Gold in the Coming Economy"
subtitle: "The New You"
description: "What really will bring wealth in the new economy"
date: 2026-03-04
author: "David Howe"
categories: [n1-experiment, methodology, pattern-recognition, value, AI, New Human]
sidebar: internal-workplace
---

# The Changing Landscape

## Introduction to AI Series

### What is Real Value?

I find myself stumbling with this question as I look across what is happening in the world at this moment. This is probably why I started the Fire in the Cave. For me, part of this is trying to find out what I really want to do. 

What makes my fulfilled and happy. 

The other aspect with respect to where I am at in life or the most honest one. 
We battle through narrations about what should make you happy. Finding a job or work that provides. Having a family or friends or other community that you belong to. Having a place to call home. Children. This has been what has sustained us over the generations. The chance to live the American dream.

Over the years, technology has changed or given new meaning to these basic tenets. For work, having a harder time disengaging or always being on. Community could include social media or maybe replaced by social media. Still need or desire a place for home, but for some it is moving back in with the parents. Children, changes in the other portions of the dream has affected this also.

From the Global Opt out posts, we found in different countries and cultures, the same stressors are appearing on the basic tenets which is driven down from the previous generations. Not realizing that these pressures do not help or if many of these core items are unobtanium, how does pressure help?

The next 500-lb gorilla coming on the pressure scene is of course AI. AI is coming to take your job. Need to keep pace because of AI. AI will run everything. Move to manual labor or the trades for a career. There is nothing wrong with that. My father had his own business in the trades. 

I could not do it and that is why I ended up here. I started having these thoughts around 5 years ago before the hype cycle. More in general with my career again. 

What was important to me and really what was wealth?

Now circling again, but from a new energized mind set.

What changed? 

I started to really look at AI. How it is being used. How I can use it. Really use it. How it will eventually be used. We are not there yet with it. 

As I did this. Looking. Thinking. Learning. I got excited. Really excited. 

If we look back in history, back at early 1920s. Ford setting up the first manufacturing system for the Model T. If you had a chance or were around back then with some imagination about the new possibilities, what would you have done. Looking at how prosperity started by others learning from the system and applying to other areas. Those who set up the companies that provided the materials. Those who set up companies to build the factories. The other infrastructure to support manufacturing. 

Believe it or not. I think that we are are a similar place again. Those companies setting up AI now they believe that they have direction set, but already things are changing from when ChatGPT was released. Agentic AI or multiple AI models are now the new rage, but even this is probably going to change. 

What sets the model really is who is willing to pay and they set what it does. We are really still in that stage.

Ok. Enough of the rah rah. We need to really look at the rollout out and more importantly the generation of the AI models. Really take a look at how the companies attained the model data. The companies scrapped the internet, books, reddit posts and other accessible data without the author's permissions. Currently they are dealing with lawsuits over this practice, but regardless the models have been deployed.

The manner with which OpenAI, Claude, Google, X and others strip mined the knowledge bases to obtained their data to model. One could compare to mining for BTC, rare earth minerals, silver, gold, copper and other precious metals and minerals. 

This tells you what the AI companies really value. Same level compared to miners that mine more expensive commodities. Let that sink in. Your posts. Your thoughts. Your word choices. Your writing. BTC price?

Yet, the narrative is that the AI will be taking many roles. You have to change how you work or you fall behind. I am not the depressed though. What if I told you that I hope to convince you that these could be the best times ever. You have what the AI companies will need and desperately need.

I will be presenting all of this in future posts. Problems with the AI models. Opportunities for new positions or how to use your own models to navigate this wave. What skills I think will be important. How I am developing skills for the change. How to really come out on top. I would love to tell you that I know exactly what will happen.

I cannot. I can tell you that as I bring in the new posts. We will be working on skills the will help you regardless of what you want to do. 
